config/routes.rb
Hoto::Application.routes.draw do
  get "rules/show"
  get "sessions/new"
  get "sessions/create"

  resources :users

  resources :squares

  resources :games

  resources :rules

  resources :sessions, only: [:new, :create, :destroy]
  
  get "game/index"
  root to:  'games#index'
  post "games/:id/place" => 'games#click_to_place'
  post "games/:id/end" => 'games#end_turn'
  post "games/:id/topplecheck" => 'games#topplecheck'
  post "games/:id/topplecall" => 'games#topplecall'
  post "games/:id/resign" => "games#resign"
  get "available_games_refresh" => 'games#available_games_refresh'

  

end

app/views/layouts/_header.html.erb
<div id ="header">
    <!-- <h1 id="hoto-title"><%= link_to "Hoto", '/' %></h1> -->
    <%= link_to (image_tag "hotologo.png", :class => "logo-size"), '/' %>
    <nav id="navbar">  
      <h4>
        <% if current_user %>

          Signed in as <%= link_to current_user.name, user_path(current_user) %> (<%= current_user.current_rating %>) <%= link_to "Log out ", session_path("current"), method: :delete, :style => "margin-left: 5px;" %>
        <% else %>
          <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
        <% end %>
        <%= link_to "Rules", rules_path %>
      </h4>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoto</title>
  <%= javascript_include_tag "https://js.pusher.com/2.2/pusher.min.js" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>